# Generated by Django 3.0.3 on 2020-08-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسندگان'},
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='تصویر نویسنده'),
            preserve_default=False,
        ),
    ]
