# Generated by Django 3.0.3 on 2020-08-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_writer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Writer',
        ),
    ]
