# Generated by Django 3.0.3 on 2020-08-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200814_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='blogname',
        ),
    ]
