# Generated by Django 3.0.3 on 2020-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_writer_blogname'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='position',
            field=models.CharField(choices=[('w', 'نویسنده'), ('g', 'گرافیک'), ('p', 'برنامه نویس')], default=1, max_length=1, verbose_name='جایگاه'),
            preserve_default=False,
        ),
    ]
